### ISSUE TITLE
Cosumnes floodplain Data Source 

### ISSUE THREAD

**Issue by ErinCain** [FlowWest/cvpiaHabitat#154]
Current Data Source description for Cosumnes is:
**Data Source:** [Mark Gard](mailto:mark_gard@fws.gov)
Mark Gard developed a flow-floodplain area relationship for the Cosumnes based on a UC Davis 1-D HEC-RAS model. 
(@mtompkins1101 when you do a review of the docs let us know if this is okay as a placeholder until the report comes out.) 

Need to update when the FY-19 report comes out. @thesadie

**Comment by mtompkins1101** [comment]
Hi Erin-

See below a minor edit to the description:

**Comment by ErinCain** [comment]
Will change that when I make the edits to that pull request! Thanks
