### ISSUE TITLE
Replace Winter Run Life Cycle Model reference document.

### ISSUE THREAD

**Issue by mtompkins1101** [FlowWest/cvpiaHabitat#186]
For all model regions that use habitat input data from the Winter Run Life Cycle Model (all Sacramento River reaches, Sutter Bypass, Yolo Bypass, and Delta), use this document: https://swfsc.noaa.gov/publications/CR/2017/2017Hendrix.pdf and update the reference to Hendrix et al 2017.

**Comment by isabellekavanagh** [comment]
Okay sounds good!

**Comment by isabellekavanagh** [comment]
done!
