### ISSUE TITLE
Add shapefile and kmz of Sutter, Yolo, and Delta habitat extents

### ISSUE THREAD

**Issue by mtompkins1101** [FlowWest/cvpiaHabitat#187]
On Delta and Bypass documentation pages, update data source sentence to read: 
Data Source: Central Valley Floodplain Evaluation and Delineation (CVFED) HEC-RAS hydraulic model refined for use in the NOAA-NMFS Winter Run Chinook Salmon life cycle model. The ESRI shapefile and Google Earth kmz file here [link to assett from Sadie - make sure folder also includes kmz I emailed] show the delineation of the bypass and Delta regions used to generate habitat inputs.

**Comment by thesadie** [comment]
@isabellekavanagh please add the following asset to the bypass and delta docs
`https://cvpiahabitat-r-package.s3-us-west-2.amazonaws.com/delta_bypass_extents.zip`

**Comment by isabellekavanagh** [comment]
done!
