### ISSUE TITLE
Fix Sutter Bypass reach extent names.

### ISSUE THREAD

**Issue by mtompkins1101** [FlowWest/cvpiaHabitat#188]
In the habitat input documentation (both floodplain and instream if both still exist), change the following text:

[1, , ] sutter1 = to Moulton Weir
[2, , ] sutter2 = to Colusa Weir
[3, , ] sutter3 = to Tisdale Weir
[4, , ] sutter4 = below Tisdale Weir

to 

Sutter1 = Butte Sink from Rotavele to Moulton Weir
Sutter2 = Butte Sink from Moulton Weir to Colusa Weir
Sutter3 = Sutter Bypass from Colusa Weir to Tisdale Weir
Sutter4 = Sutter Bypass from Tisdale Weir to the Sacramento River

**Comment by isabellekavanagh** [comment]
done!
