### ISSUE TITLE
American River Spawning Habitat

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#189]
Mark Gard's data in IFIM spreadsheet does not match pdf source data

**Comment by isabellekavanagh** [comment]
First section of data in 'American" tab of IFIMWUA spreadsheet does not match pages 91-107 of https://s3-us-west-2.amazonaws.com/cvpiahabitat-r-package/cvpia-sit-model-inputs/ARWA-702.pdf.

**Comment by isabellekavanagh** [comment]
Cannot find data in next section on IFIMWUA 'American' tab from this pdf: https://s3-us-west-2.amazonaws.com/cvpiahabitat-r-package/cvpia-sit-model-inputs/AmericanRiver1985IFIM.PDF

**Comment by mtompkins1101** [comment]
Data in the table starting on row 34 of the American tab of the IFIMWUA spreadsheet is an average WUA calculated from the tables for each reach.

**Comment by isabellekavanagh** [comment]
issue #1: isabelle mistake - double check description of data sources with what code is actually reading, could be inconsistent (in this case description doesn't precisely say where data reading from, but code reading from american_river_spawning_wua.csv for spawning data)

**Comment by mtompkins1101** [comment]
Talk to Hammersmark to confirm if we should just use the AWRA 2017 habitat data as is on page B-10 (91 of the PDF) or if he will be providing new and improved spawning data.
