### ISSUE TITLE
bear river instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#23]
who: @ErinCain
what: finish markdown edits

**Comment by ErinCain** [comment]
Looks good just need to go over data description with mark.

**Comment by mtompkins1101** [comment]
Made minor revisions to description in Google Sheet. Questions for Mark Gard:
1. What information from https://s3-us-west-2.amazonaws.com/cvpiahabitat-r-package/cvpia-sit-model-inputs/Holton1985_BearRiverIFIM.PDF did you use to get the spawning WUA in IFIMWUA (PDF page 21 has suitability not WUA)?
2. Is there any other habitat data for Bear River?

**Comment by thesadie** [comment]
new data from re-licensing
https://sswdrelicensing.com/home/documents/relicensing-docs/
FLA aquatic resources
weight them by length

**Comment by ErinCain** [comment]
I was not able to find the reach lengths in the report but I did trace on google earth to find the reach lengths based on the map given. I digitized the plots into a csv file and then I scaled by length and converted to sqft/1000ft
