### ISSUE TITLE
butte instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#24]
finish markdown edits

**Comment by ErinCain** [comment]
Wait on until further conversation with Mark Gard.

**Comment by mtompkins1101** [comment]
Questions for Mark Gard:
1. For spawning habitat, values for Below Centerville don't match values in IFIMWUA
2. IFIMWUA for spawning was not length - weighted. Best to weight?
3. For rearing, IFIMWUA data is only for Lower Butte? Source document DeSabla includes Middle Butte. Why isn't Middle Butte data include in IFIMWUA? How should it be included?

**Comment by ErinCain** [comment]
Main thing to finalize by talking with Mark Gard is what data should we use. 
Is there a reason that data in IFIMWUA is limited to certain reaches or can we use all the reaches?

**Comment by thesadie** [comment]
spawning: use data from report for below centerville
for fall run - use below centerville 
for spring run - use both
for steelhead - use both


rearing:
for fall run - use lower butte
for spring run - use both
for steelhead - use both

**Comment by ErinCain** [comment]
Used both above and below centerville for SR spawning but SR is the only data. So using that to represent FR. 

For rearing I just did FR and used lower butte because there are no reach lengths anywhere to combine both. Maybe we can find these and add in ST and SR later.
