### ISSUE TITLE
calaveras instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#25]
finish markdown edits

**Comment by ErinCain** [comment]
The data for Calaveras is now in raw-data but I need help to scale the reaches before I can change the documentation.

**Comment by ErinCain** [comment]
Data is scaled by reach and the new scaled data is imputed into the overall documentation. Documentation is finished for Calaveras. May need to update model with this new data.

**Comment by thesadie** [comment]
@ErinCain 
- move the raw data from data-raw/Calaveras_all_reaches.xlsx to data-raw/calaveras/Calaveras_all_reaches.xlsx
