### ISSUE TITLE
clear instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#26]
finish markdown edits

**Comment by ErinCain** [comment]
Why is FR spawn wua set to 13000 for all flow values? 
All species values for spawning are low. Not sure if this is scaling error or if these are okay.

**Comment by mtompkins1101** [comment]
@thesadie can you confirm that the values from IFIMWUA are weighted by study reach length and then added to give a WUA for the entire watershed? If this is the case then the reference description in the Google Sheet is complete.

**Comment by ErinCain** [comment]
Update with Mark's edits to the data description on the CVPIA Instream spreadsheet.

**Comment by ErinCain** [comment]
Comment on reasoning for 13000 fixed value  based on expert feedback stating that the WUA results are underestimating actual habitat. 

i will check the code to answer marks previous question.

**Comment by ErinCain** [comment]
The Steelhead and Spring Run Spawning values are very low in the original IFIMWUA spreadsheet and in the source FWS documents. Ask Mark Gard why these values are so low.
