### ISSUE TITLE
cosumnes instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#27]
finish markdown edits

**Comment by ErinCain** [comment]
Modeled as a combination of moklunme and calaveras so no data source. Should we do documentation like the other mean WUA areas?

**Comment by thesadie** [comment]
You can use the text Mark created for the upper sac tribs that use the same method

**Comment by ErinCain** [comment]
Alright will use that text for data description.

**Comment by ErinCain** [comment]
Finished with the exception of the data source description where we need watershed area = X; active channel width = Y; 2-year flow = Z for cosumnes, calaveras, and mokelume river. I need to figure out how to find watershed area and then use channel area to find channel width.

**Comment by ErinCain** [comment]
Check to make sure that updated Mokelume data used in cosumnes.
