### ISSUE TITLE
cottonwood instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#28]
finish markdown edits

**Comment by ErinCain** [comment]
Confusion on the data source(s) that instream data comes from. Mark provided some clarifications on the CVPIA instream spreadsheet.

**Comment by ErinCain** [comment]
@mtompkins1101 talk to Mark Gard about where the combined data in the IFIMWUA cottonwood.

**Comment by ErinCain** [comment]
I need to go through the graphs in the 2013 PG&E report and use graph converter to input data from 3 reaches .

**Comment by mtompkins1101** [comment]
Talk to Mark Gard: Spawning data is consistent with the source document CDFW 1979 pages 11-15. We don't see data in the IFIMWUA spreadsheet for the rearing habitat three separate curves on pages 46-47 of the USFWS 2014 report. Questions:
1. Should we combine all three curves and then weight the totals by the study reach lengths?
2. If not, why did you divide the rearing values in IFIMWUA by 10.6 miles - same as 1979 spawning data?

**Comment by ErinCain** [comment]
I was going to use the UFWS 2013 study graphs on pages 46-47 to take rearing data from all 3 reaches and then combine these to use as new rearing data but I cannot find the lengths of the reaches in the study. Without the lengths we will not be able to weigh the reaches correctly to get a total WUA. Not sure what to do about this seems like another thing to ask Mark Gard @mtompkins1101.

**Comment by ErinCain** [comment]
I will find the lengths for the 3 reaches so that we can add the curves from the study and weight them with the proper lengths.

**Comment by ErinCain** [comment]
Found lengths using Google Earth and used graph converter to input data from 3 reaches.  Found the weighted WUA values but would like to check that I did it in the right way my values seem small. Also may want to get more data points from the graphs in PG&E report.

**Comment by ErinCain** [comment]
Follow up with expert outreach cvpiaHabitat::watershed_lengths expert column.

**Comment by thesadie** [comment]
@ErinCain 
line 51 - change to italics

**Comment by thesadie** [comment]
we using the reach where the flows match up with calsim node
lowest reach, doesn't use upper reaches wua which are lower at same flows

**Comment by ErinCain** [comment]
I reverted the in stream doc back to the original data. @mtompkins1101 can you help me edit the source details to reflect why we only want to use the lowest reach because of the calsim node?
