### ISSUE TITLE
cow instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#29]
finish markdown edits

**Comment by ErinCain** [comment]
Almost done just need to go over the finalized data description with Mark.

**Comment by mtompkins1101** [comment]
Questions for Mark Gard:
1. How should juv and fry rearing data from South Cow Boero and Valley Floor reaches be combined to scale to all of Cow Creek?
2. Any spawning WUA data available? If not, what should we use?

**Comment by ErinCain** [comment]
Currently data for rearing combines the reaches and scales by length so go back and fix this if that is incorrect.

**Comment by thesadie** [comment]
No spawning data for cow creek, regional approximation
