### ISSUE TITLE
merced instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#30]
finish markdown edits

**Comment by ErinCain** [comment]
I cannot find the data source. Links to a paper about the Lower American River. Need to do some more investigating.

**Comment by thesadie** [comment]
@mtompkins1101 will you help @ErinCain find the merced data source

**Comment by mtompkins1101** [comment]
Questions for Mark Gard:
1. Can we use the steelhead data from all three subreaches?
2. If so, can we weight them the same as you did for the Chinook data?

**Comment by ErinCain** [comment]
Finished with the exception of Mark Gard Steelhead Questions.

**Comment by thesadie** [comment]
@ErinCain 
line 40 - change to italics

**Comment by thesadie** [comment]
Include all 3 reaches for steelhead, weighted by study reach length
