### ISSUE TITLE
sacramento instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#31]
finish markdown edits

**Comment by ErinCain** [comment]
Not sure what data reach of the river listed in IFMWUA.xlsx to use.

**Comment by thesadie** [comment]
the sacramento instream data comes from a different source not IFIMWUA

**Comment by ErinCain** [comment]
Need help interpenetrating and wrangling data given to make it into a similar format as the data that we are using for the other docs. I created a mark down and have tried to understand the data that is in clean_Sacramento_instream but I need help interpreting the 4 regions of rearing and one region of spawning(with both in and out values).

**Comment by mtompkins1101** [comment]
@thesadie can you provide a location of the source data spreadsheet from NMFS?

**Comment by mtompkins1101** [comment]
@thesadie I need your help describing where the Sacramento River spawning habitat area comes from. This is not in the Winter Life Cycle model data.

**Comment by mtompkins1101** [comment]
@thesadie we need a path or link to the correct NMFS Winter Run Life Cycle Model habitat data spreadsheet.

**Comment by mtompkins1101** [comment]
@thesadie we need your help explaining how the Gard IFIMWUA data for spawning was translated for use in the SIT model - it's not entirely clear from the CVPIAHabitat page.
