### ISSUE TITLE
tuolumne instream docs

### ISSUE THREAD

**Issue by thesadie** [FlowWest/cvpiaHabitat#34]
finish markdown edits

**Comment by ErinCain** [comment]
Finished markdown for Tuolumne. Please let me know what you think, 

I did have a question about whether or not to include the Steelhead in the rearing plot? Right now it is only the salmon because the description said salmon but I can add the steelhead Juv and fry in and edit the description.

**Comment by thesadie** [comment]
Please add a section for steelhead plots, then I will review

**Comment by ErinCain** [comment]
Alright will do now.

**Comment by ErinCain** [comment]
The Steelhead plots should be included now.

**Comment by mtompkins1101** [comment]
Updated description in Google Sheet. @thesadie two questions:
1. Will we update this with VA data provided by Districts? If so, when?
2. Do we need to say anything in the documentation about with / without cover in the source document for the data?

**Comment by thesadie** [comment]
@ErinCain 
i sent you the update va data, we can look together to update

**Comment by ErinCain** [comment]
The update VA data looks similar for spawning but the VA rearing data goes to significantly higher flows. It looks like the updated VA data only has Chinook no Steelhead.
