### ISSUE TITLE
stanislaus instream docs

### ISSUE THREAD

**Issue by ErinCain** [FlowWest/cvpiaHabitat#42]

**Comment by ErinCain** [comment]
@mtompkins1101  Spawning data does not match up with report.( https://cvpiahabitat-r-package.s3-us-west-2.amazonaws.com/cvpia-sit-model-inputs/Aceituno1993_StanislausRiverIFIMStudy.pdf) Maybe another question for Mark Gard.

**Comment by thesadie** [comment]
For spawning, 93 study is most current. Use reach total (sqft) find total length of reach to create wua (sqft/1000ft) or scale by length wuas of the 4 reaches. Mark Gard to reach total divided 50 miles.

Rearing is from later study, one of the >2014 annual reports.

**Comment by ErinCain** [comment]
For spawning scaled 4 reaches total length is 24 mi. Length of each reach is in stanislaus_spawning_data.csv. 

I think Gard data is about half the size of combined weighted spawning results which makes sense given he used 50 mi as total reach length when in reality it is only 24 mi. 

Found correct rearing data in FWS annual report 2012.
